# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7feee04d974822305e9e045de432176d1168058c78936d33c511cc616afc976094e2d52e96521e10ca0a3866236ccf59aec53b0289b81483a20dc8323dd22d4c

test:
  secret_key_base: 8acef7712dc98f78cab5db5b73743921578413e3b8735d7047c840c70d901d43185d19b6d5340788aa10aea3345a7efdcfdd2aae3d4748dc5ef9cf095c857f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
